src/api/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from .api_views.student_views import student_view, student_detail
from .api_views.teacher_views import teacher_view, teacher_detail
from .api_views.user_views import user_detail, user_view

router = routers.DefaultRouter()
#router.register(r'students', student_view)

urlpatterns = [
   #path('', include(router.urls)), 
   path('student', student_view),
   path('student/<int:pk>', student_detail),

   path('teacher', teacher_view),
   path('teacher', teacher_detail),

   path('user', user_view),
   path('user/<int:pk>', user_detail)
]

src/base/urls.py
from django.urls import path
from .views.address_views import *


app_name = 'address'
urlpatterns = [
    path('address', add, name = 'add'),
    path('', list, name = 'list'),
    path('update/<int:id>', edit, name = 'edit'),
    path('delate/<int:id>', edit, name = 'delate'),
]

src/monetabv1_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('base/', include('base.urls')),
    path('', include('school.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('', include('user.urls')),
    path('report/', include('report.urls')),

    path('api/', include('api.urls')),
]

src/report/urls.py
from django.urls import path
from report.views.students_report import *
from report.views.users_report import *

app_name = 'report'
urlpatterns = [
    path('', report, name= 'report'),
    path('pdf/<str:report_type>/', generate_pdf_report, name='generate_pdf'),
    path('excel/<str:report_type>/', generate_excel_report, name='generate_excel'),
]

src/school/urls.py
from django.urls import path
from school.views.school_views import *
from school.views.app_settings_views import *


app_name="school"
urlpatterns = [
    path('school',list,name="list"),
    path('school/add/',add,name="add"),
    path('school/update/<int:id>',edit,name="edit"),
    # path('delete/<int:id>',edit,name="delete"),
    path('school/details/<int:id>',edit,name="details"),

    path('appsetting',sett_list,name="sett_list"),
    path('add_setting/',add_setting,name="add_setting"),
    path('edit_setting/<int:id>',edit_setting,name="edit_setting"),
    path('delete_setting/<int:id>',delete_setting,name="delete_setting"),
    path('setting_details/<int:id>',setting_details,name="setting_details"),

]

src/student/urls.py
from django.urls import path
from student.views.student_view import * 
from student.views.absence_view import * 
from student.views.student_cards_view import *



app_name="student"
urlpatterns = [
    path('', list,name="list"),
    path('add',add,name="add"),
    path('add_abs',add_abs,name="add_abs"),
    path('list_abs',list_abs,name="list_abs"),
    path('update_abs',update_abs,name="updateabs"),
    path('add_card',add_card,name="add_card"),
    path('list_card',list_card,name="list_card"),
    path('update/<int:id>',edit,name="edit"),
    path('delete/<int:id>',delete,name="delete"),
]

src/user/urls.py
from django.urls import path
from user.views.user_views import *
from user.views.role_user_views import *


app_name = 'user'
urlpatterns = [
    path('login/', userlogin, name='login'),
    path('logout/',userlogout, name='logout'),
    path('user/add', add_or_edit, name = 'add'),
    path('users', list, name = 'list'),
    path('user/<int:id>/update', add_or_edit, name = 'edit'),
    path('toggle_status/<int:id>/', user_status, name='status'),
    

    path('user/Add-role/',add_role,name="add_role"),
    path('user/List-role/',list_role,name="list_role"),
    path('user/<int:id>/edit-role',edit_role,name="edit_role"),
    path('user/<int:id>/delete-role',delete_role,name="delete_role"),
]

src/base/models/address_model.py
from django.db import models

from base.models.helpers.date_time_model import DateTimeModel


class AddressModel(DateTimeModel):
    city = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    country = models.CharField(max_length=255)

src/base/models/person_model.py
from django.db import models

from base.models.helpers.date_time_model import DateTimeModel

from user.models import gender_model

class PersonModel(DateTimeModel):
    GENDER_CHOICES = (
        ('M','MALE'),
        ('F','FEMALE'),
        ('O','OTHER'),
     )
    
    user = models.OneToOneField('user.UserModel', on_delete=models.CASCADE) 
    address = models.OneToOneField('base.AddressModel', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birthday = models.DateField()
    phone_number = models.CharField(max_length=20)
    url_picture = models.URLField()
    gender = models.CharField(max_length=10, choices=gender_model.Gender.choices)

    class Meta:
        abstract = True

src/base/forms.py
from django import forms
from .models.address_model import AddressModel

class AdressFoms(forms.ModelForm):
    class Meta:
        model = AddressModel
        fields = "__all__"
        

src/base/views/address_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from school.views.decorator_views import check_settings
from base.forms import AdressFoms
from base.models.address_model import AddressModel

# Create your views here.
@login_required(login_url='user:login')
@check_settings
def add(request):
    context={"title":"Ajouter Adress"}

    if request.method == "POST":
        print(request.POST)
        form =AdressFoms(request.POST)
        context["form"] = form
        if form.is_valid():
            print("form is valid")
            print(form.cleaned_data)
            form.save()
            return redirect('student:list')
        else:
            return render(request,"base/adress_form.html")

    # context={'elev_form':elev_form}
    form = AdressFoms()
    context["form"] = form

    return render(request,"base/address_form.html",context)


@login_required(login_url='user:login')
@check_settings
def list(request):
    address = AddressModel.objects.all()
    context = {
        'address': address,
        }
    
    return render(request, "base/address_list.html", context)


@login_required(login_url='user:login')
@check_settings
def edit(request, id):
    teacher = AddressModel.objects.get(id=id)

    context = {"title":"Modifier adresse"}

    if request.method == "POST":
        form = AdressFoms(request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            return redirect('address:list')
        
    address_form = AdressFoms(instance = teacher)

    context["form"] = address_form
    
    return render(request,"base/address_form.html",context)

@login_required(login_url='user:login')
@check_settings
def delete(request, id):
    address = AddressModel.objects.get(id = id)
    address.delete()
    return redirect('address:list')

src/base/views/middleware.py
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth import logout
from school.models import SchoolModel, AppSettingsModel
from django.contrib.auth.decorators import login_required

# @login_required(login_url='user:login')
class EnsureSettingsMiddleware:
    pass
    # def __init__(self, get_response):
    #     self.get_response = get_response

    # def __call__(self, request):
    #     # Les URL à ignorer pour éviter la boucle de redirection
    #     excluded_paths = [
    #         reverse('user:login'),        # URL de la page de connexion
    #         reverse('user:logout'),       # URL de la page de déconnexion
    #         '/school/add/',          # URL pour ajouter une école
    #         '/school/add_setting/',  # URL pour ajouter les paramètres de l'application
    #         '/admin/',               # URL pour accéder à l'admin Django
    #     ]

    #     # Vérifier si l'utilisateur est connecté
    #     if request.user.is_authenticated:
    #         # Si l'utilisateur est un superuser, on peut lui permettre d'accéder
    #         # if request.user.is_superuser:
    #         #     return self.get_response(request)

    #         # Si l'utilisateur tente d'accéder à une page non exclue
    #         if not any(request.path.startswith(path) for path in excluded_paths):
    #             # Vérifier si les paramètres de l'application et de l'école existent
    #             app_settings_exist = AppSettingsModel.objects.exists()
    #             school_settings_exist = SchoolModel.objects.exists()

    #             # Si les paramètres ne sont pas encore configurés
    #             if not app_settings_exist:
    #                 return redirect('/school/add_setting/')  # Rediriger vers l'ajout des paramètres
    #             if not school_settings_exist:
    #                 return redirect('/school/add/')  # Rediriger vers l'ajout de l'école

    #     # Si tout est correct ou l'utilisateur n'est pas connecté, on continue normalement
    #     response = self.get_response(request)
    #     return response

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Bloc</title>
  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
 {% block static_link %}{% endblock static_link %}
  <style>
    body {
      font-family: Arial, sans-serif;
    }

    .sidebar {
      height: 100vh;
      position: fixed;
      top: 0;
      left: 0;
      width: 250px;
      background-color: #f8f9fa;
      padding-top: 20px;
      border-right: 1px solid #dee2e6;
    }

    .sidebar a {
      display: block;
      color: #333;
      padding: 10px 15px;
      text-decoration: none;
    }

    .sidebar a:hover {
      background-color: #007bff;
      color: white;
    }

    .content {
      margin-left: 250px;
      padding: 20px;
    }
  </style>
</head>

<body>
  <!-- Sidebar -->
  <div class="sidebar">
    <h2 class="text-center">Menu</h2>
    <div class="user-info text-center">
      <p><strong>Utilisateur :</strong> {{ user.pseudo }}</p>
      <p><strong>École :</strong> {{ school.name }}</p>
    </div>
    <a href="{% url 'dashboard:dashboard' %}">Tableau de bord</a>
    <a href="{% url 'school:edit_setting' 1  %}">Paramètres</a>
    <a href="{% url 'school:edit' 1 %}">Ecoles</a>
    <a href="{% url 'user:list_role' %}">Rôles</a>
    <a href="{% url 'user:list' %}">Utilisateurs</a>
    <a href="{% url 'address:list' %}">Adresses</a>
    <a href="{% url 'teacher:list' %}">Enseignants</a>
    <a href="{% url 'student:list' %}">Elèves</a>
    <a href="{% url 'report:report' %}">Raports</a>
    <a href="{% url 'user:logout' %}">Se déconnecter</a>
  </div>

  <!-- Main Content -->
  <div class="content">
    {% block content %}
    {% endblock content %}
  </div>

  <!-- Bootstrap JS and dependencies -->
  <script src="{% static 'js/script.js' %}"></script>
  {% block confirmation_js %}
  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>