src/api/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from .api_views.student_views import student_view, student_detail
from .api_views.teacher_views import teacher_view, teacher_detail
from .api_views.user_views import user_detail, user_view

router = routers.DefaultRouter()
#router.register(r'students', student_view)

urlpatterns = [
   #path('', include(router.urls)), 
   path('student', student_view),
   path('student/<int:pk>', student_detail),

   path('teacher', teacher_view),
   path('teacher', teacher_detail),

   path('user', user_view),
   path('user/<int:pk>', user_detail)
]

src/monetabv1_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('base/', include('base.urls')),
    path('', include('school.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('', include('user.urls')),
    path('report/', include('report.urls')),

    path('api/', include('api.urls')),
]

src/student/urls.py
from django.urls import path
from student.views.student_view import * 
from student.views.absence_view import * 
from student.views.student_cards_view import *



app_name="student"
urlpatterns = [
    path('', list,name="list"),
    path('add',add,name="add"),
    path('add_abs',add_abs,name="add_abs"),
    path('list_abs',list_abs,name="list_abs"),
    path('update_abs',update_abs,name="updateabs"),
    path('add_card',add_card,name="add_card"),
    path('list_card',list_card,name="list_card"),
    path('update/<int:id>',edit,name="edit"),
    path('delete/<int:id>',delete,name="delete"),
]

src/student/models/absence_model.py
from django.db import models

from base.models.helpers.date_time_model import DateTimeModel




class AbsenceModel(DateTimeModel):
    student = models.ForeignKey('student.StudentModel',related_name='absence_student_ids', on_delete=models.CASCADE)
    absence_date = models.DateField()
    absence_number = models.IntegerField()

src/student/models/student_cards_model.py
from django.db import models

from base.models.helpers.date_time_model import DateTimeModel




class StudentCardsModel(DateTimeModel):
    student = models.ForeignKey('student.StudentModel', on_delete=models.CASCADE)
    reference = models.CharField(max_length=255)
    issue_date = models.DateField()
    expiration_date = models.DateField()

src/student/models/student_model.py
from django.db import models

from base.models.person_model import PersonModel


class StudentModel(PersonModel):
    
    matricule = models.CharField(max_length=255)
    phone_number_father = models.CharField(max_length=20)

src/student/forms/absence_form.py
from django import forms
from student.models.absence_model import AbsenceModel


class AbsenceFoms(forms.ModelForm):
    class Meta:
        model = AbsenceModel
        fields = "__all__"
        widgets={
            'absence_date':forms.DateInput(attrs={'type':'date'}),
        }
        

src/student/forms/student_cards_form.py
from django import forms
from student.models.student_cards_model import StudentCardsModel


class StudentCardFoms(forms.ModelForm):
    class Meta:
        model = StudentCardsModel
        fields = "__all__"
        widgets={
            'issue_date':forms.DateInput(attrs={'type':'date'}),
            'expiration_date':forms.DateInput(attrs={'type':'date'}),
            
        }
       

src/student/forms/student_form.py
from django import forms
from student.models.student_model import StudentModel
from base.models.person_model import PersonModel

class StudentFoms(forms.ModelForm):
    class Meta:
        model = StudentModel
        fields = "__all__"
        widgets={
            'birthday':forms.DateInput(attrs={'type':'date'}),
            'gender' :forms.RadioSelect(choices=PersonModel.GENDER_CHOICES),
        }

src/student/views/absence_view.py
from django.shortcuts import render, redirect
from student.models.absence_model import AbsenceModel
from student.forms.absence_form import AbsenceFoms
from django.contrib.auth.decorators import login_required
from school.views.decorator_views import check_settings


@login_required(login_url='user:login')
@check_settings
def add_abs(request):
    context={"title":"Ajout Absence"}

    if request.method == "POST":
        print(request.POST)
        formA =AbsenceFoms(request.POST)
        context["formA"] = formA
        if formA.is_valid():
            print("form is valid")
            print(formA.cleaned_data)
            formA.save()
            return redirect('student:list_abs')
        else:
            return render(request,"student/absence.html")

    # context={'elev_form':elev_form}
    formA = AbsenceFoms()
    context["formA"] = formA

    return render(request,"student/absence.html",context)

@login_required(login_url='user:login')
def list_abs(request):
    absences = AbsenceModel.objects.all()
    absence_count = AbsenceModel.objects.count()

    context = {
        'absences':absences,
        'absence_count':absence_count
        
    }
    return render(request, "student/list_abs.html", context)


@login_required(login_url='user:login')
def update_abs(request,id):
    absence = AbsenceModel.objects.get(id=id)
    
    context={"title":"Modifier Absence"}

    if request.method == "POST":
        print(request.POST)
        formA =AbsenceFoms(request.POST, instance=absence)
        context["formA"] = formA
        if formA.is_valid():
            print("form is valid")
            print(formA.cleaned_data)
            formA.save()
            return redirect('student:list_abs')
        else:
            return render(request,"student/absence.html")

    # context={'elev_form':elev_form}
    formA = AbsenceFoms(instance=absence)
    context["formA"] = formA

    return render(request,"student/absence.html",context)

src/student/views/student_cards_view.py
from django.shortcuts import render, redirect
from student.forms.student_cards_form import StudentCardFoms
from student.models.student_cards_model import StudentCardsModel
from django.contrib.auth.decorators import login_required
from school.views.decorator_views import check_settings


@login_required(login_url='user:login')
@check_settings
def add_card(request):
    context={"title":"Carte Etudiant"}

    if request.method == "POST":
        print(request.POST)
        formS =StudentCardFoms(request.POST)
        context["formS"] = formS
        if formS.is_valid():
            print("form is valid")
            print(formS.cleaned_data)
            formS.save()
            return redirect('student:list_card')
        else:
            return render(request,"student/student_cards.html")


    formS = StudentCardFoms()
    context["formS"] = formS

    return render(request,"student/student_cards.html",context)


@login_required(login_url='user:login')
@check_settings
def list_card(request):
    studentCardss = StudentCardsModel.objects.all()
    carte_count = StudentCardsModel.objects.count()
    context = {
        'studentCardss':studentCardss,
        'carte_count':carte_count
        
    }
    return render(request, "student/list_card.html", context)

src/student/views/student_view.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from student.forms.student_form import StudentFoms
from student.models.student_model import StudentModel
from django.contrib.auth.decorators import login_required
from school.views.decorator_views import check_settings


@login_required(login_url='user:login')
@check_settings
def list(request):
    query = request.GET.get('q')
    if query:
        students = StudentModel.objects.filter(
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query) |
            Q(matricule__icontains=query)
        )
    else:
        students = StudentModel.objects.all()

    student_count = students.count()
    context = {
        'students': students,
        'student_count': student_count,
        'query': query,
    }
    return render(request, "student/student_list.html", context)


@login_required(login_url='user:login')
@check_settings
def add(request):
    context={"title":"Ajouter Eleve"}

    if request.method == "POST":
        print(request.POST)
        student_form =StudentFoms(request.POST)
        context["student_form"] = student_form
        if student_form.is_valid():
            print("student_form is valid")
            print(student_form.cleaned_data)
            student_form.save()
            return redirect('student:list')
        else:
            return render(request,"student/student_form.html")

    student_form = StudentFoms()
    context["student_form"] = student_form

    return render(request,"student/student_form.html",context)


@login_required(login_url='user:login')
@check_settings
def edit(request, id ):
    student = StudentModel.objects.get(id=id)
    context = {"title":"Modifier eleve"}
    if request.method == "POST":
        student_form = StudentFoms(request.POST, instance=student)
        if student_form.is_valid():
            student_form.save()
            return redirect('student:list')
        
    form = StudentFoms(instance = student)

    context["student_form"] = student_form

    return render(request,"student/student_form.html",context)

@login_required(login_url='user:login')
def delete(request ,id):
    student = StudentModel.objects.get(id = id)
    student.delete()
    return redirect('student:list')

src/templates/student/absence.html
{% extends 'base.html' %}

{% block content %}
      <!-- Main Content -->
      <div class="flex-1 p-6">
        <a
          href="{% url 'student:list_abs' %}"
          class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 mr-2"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 19l-7-7 7-7"
            />
          </svg>
          Retour
        </a>
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            {{title}}
          </h1>
          <form action="" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            {% csrf_token %}

             {{formA}}
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <button
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </button>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
          </form>
        </div>
      </div>
{% endblock content %}

src/templates/student/list_abs.html
{% extends 'base.html' %}
{% load static %}

    

 
{% block content %}

      <!-- Main Content -->
      <div class="flex-1 p-6">
        <div class="flex justify-between items-center mb-6">
          <h1 class="text-2xl font-semibold">Listes des absences : {{ absence_count }}</h1>
          <a
            href="{% url 'student:add_abs' %}"
            class="flex items-center text-blue-500 hover:text-blue-700"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 4v16m8-8H4"
              />
            </svg>
            Nouvelle Absence
          </a>
        </div>
        <div class="bg-white p-6 rounded-lg shadow overflow-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Nombre d'absence
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Date d'absence
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Matricule
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Nom
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Prenoms
                </th>
                
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              {% for absence in absences %}
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">{{absence.absence_number}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{absence.absence_date}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{absence.student.matricule}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{absence.student.last_name}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{absence.student.first_name}}</td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <a
                  href="#"
                    class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded"
                  >
                    Modifier
                </a>
              </td>
              </tr>
              {% endfor %}
              
            </tbody>
          </table>
        </div>
      </div>
{% endblock content %}

src/templates/student/list_card.html
{% extends 'base.html' %}
{% load static %}

    

 
{% block content %}

      <!-- Main Content -->
      <div class="flex-1 p-6">
        <div class="flex justify-between items-center mb-6">
          <h1 class="text-2xl font-semibold">Listes des cartes : {{ carte_count }}</h1>
          <a
            href="{% url 'student:add_card' %}"
            class="flex items-center text-blue-500 hover:text-blue-700"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 4v16m8-8H4"
              />
            </svg>
            Nouvelle Carte d'étudiant
          </a>
        </div>
        <div class="bg-white p-6 rounded-lg shadow overflow-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Numéro de la carte
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Date de création
                </th>
                <th
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
              >
                Date d'expiration
              </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Matricule
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Nom
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Prenoms
                </th>
                
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              {% for studentCards in studentCardss %}
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.reference}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.issue_date}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.expiration_date}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.student.matricule}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.student.last_name}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{studentCards.student.first_name}}</td>
                
              </tr>
              {% endfor %}
              
            </tbody>
          </table>
        </div>
      </div>
{% endblock content %}

src/templates/student/student_cards.html
{% extends 'base.html' %}

{% block content %}
      <!-- Main Content -->
      <div class="flex-1 p-6">
        <a
          href="{% url 'student:list_card' %}"
          class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 mr-2"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 19l-7-7 7-7"
            />
          </svg>
          Retour
        </a>
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            {{title}}
          </h1>
          <form action="" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            {% csrf_token %}

             {{formS}}
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <button
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </button>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
          </form>
        </div>
      </div>
{% endblock content %}

src/templates/student/student_confirm_delete.html
<!-- templates/students/student_confirm_delete.html -->
{% extends "base.html" %}
{% block content %}
<h1>Supprimer Étudiant</h1>
<p>
  Voulez-vous vraiment supprimer {{ student.first_name }} {{ student.last_name }}
  ?
</p>
<form method="post">
  {% csrf_token %}
  <button type="submit">Confirmer</button>
</form>
<a href="{% url 'student:list' %}">Annuler</a>
{% endblock content %}

src/templates/student/student_detail.html
<!-- templates/students/student_detail.html -->
{% extends "base.html" %} {% block content %}
<h1>Détails de l'Étudiant : {{ student.first_name }} {{ student.last_name }}</h1>
<p>Matricule: {{ student.matricule }}</p>
<p>Téléphone du père: {{ student.phone_number_father }}</p>
<a href="{% url 'student:list' %}">Retour à la liste</a>
{% endblock content %}

src/templates/student/student_form.html
<!-- templates/students/student_form.html -->
{% extends "base.html" %} {% block content %}
<h1>{% if student %}Modifier Étudiant{% else %}Ajouter Étudiant{% endif %}</h1>
<form method="post">
  {% csrf_token %} {{ student_form.as_p }}
  <button type="submit">Enregistrer</button>
</form>
<a href="{% url 'student:list' %}">Annuler</a>
{% endblock content %}

src/templates/student/student_list.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-4">
  <h1>Liste des Étudiants</h1>
  <form method="GET" action="{% url 'student:list' %}" class="form-inline">
    <input type="text" name="q" value="{{ query }}" placeholder="Rechercher un élève" class="form-control">
    <button type="submit" class="btn btn-primary ml-2">Rechercher</button>
  </form>
  <a href="{% url 'student:add' %}" class="btn btn-primary">Ajouter un Étudiant</a>
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
      <tr>
        <td>{{ student.last_name }}</td>
        <td>{{ student.first_name }}</td>
        <td>
          <a href="{% url 'student:edit' student.id %}" class="btn btn-sm btn-warning">Modifier</a>
          <a href="{% url 'student:delete' student.id %}" class="btn btn-sm btn-danger">Supprimer</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}